### PR TITLE
modified,revved pie chart

### PR DESCRIPTION
**Pull request by seansmckinley**
added param. more pythonic. uses value_counts.

### CODE REVIEW

**Comment by seansmckinley** [comment]
NaN to No response last commit

**Comment by dsoto** [comment]
This is looking good.  Now we can move into the very fine details.

Can you make small edits to conform to spacing conventions around equals and commas?
https://www.python.org/dev/peps/pep-0008/#other-recommendations

**Comment by seansmckinley** [comment]
is pie_chart_boolean in pysentani?

**Comment by dsoto** [comment]
not yet.  this is looking good to me.  do you think it is ready to merge?

**Comment by seansmckinley** [comment]
yes, I do.

**Pull request merged**
